import { Test, TestingModule } from '@nestjs/testing';
import { AskAiController } from './ask-ai.controller';
import { AskAiService } from 'src/ask-ai/ask-ai.service';
import { AuthGuard } from 'src/guards/authGuard';

describe('AskAiController', () => {
  let controller: AskAiController;
  let service: AskAiService;

  const mockAskAiService = {
    submitQuery: jest.fn(),
  };

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      controllers: [AskAiController],
      providers: [
        {
          provide: AskAiService,
          useValue: mockAskAiService,
        },
      ],
    })
      .overrideGuard(AuthGuard)
      .useValue({ canActivate: jest.fn(() => true) }) 
      .compile();

    controller = module.get<AskAiController>(AskAiController);
    service = module.get<AskAiService>(AskAiService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  describe('submitQuery', () => {
    it('should call askAiService.submitQuery with correct parameters', async () => {
      const mockUserData = { id: 1, role: 'org_admin' };
      const mockRequest = {
        user_data: mockUserData,
        body: {
          assessment_id: 123,
          section_id: 'section1',
          section_text: 'Some text',
          selection_text: 'Selected text',
          query_text: 'What is this about?',
          chat_history: [],
          ai_rewrite: true,
        },
      };

      mockAskAiService.submitQuery.mockResolvedValue({
        id: 456,
        assessment_id: 123,
        section_id: 'section1',
        query_text: 'What is this about?',
        content: 'AI-generated response',
        description: 'Generated by AI',
      });

      const result = await controller.submitQuery(mockRequest);

      expect(mockAskAiService.submitQuery).toHaveBeenCalledWith(
        mockUserData,
        mockRequest.body,
      );

      expect(result).toEqual({
        id: 456,
        assessment_id: 123,
        section_id: 'section1',
        query_text: 'What is this about?',
        content: 'AI-generated response',
        description: 'Generated by AI',
      });
    });

    it('should throw an error if askAiService.submitQuery fails', async () => {
      const mockRequest = {
        user_data: { id: 1, role: 'org_admin' },
        body: { assessment_id: 123, query_text: 'What is this about?' },
      };

      mockAskAiService.submitQuery.mockRejectedValue(new Error('Service error'));

      await expect(controller.submitQuery(mockRequest)).rejects.toThrow(
        'Service error',
      );
    });
  });
});
