#!/bin/sh
# SecondFront GameWarden hardening script for Node.js BFF Service
# Based on: https://medium.com/asos-techblog/minimising-your-attack-surface-by-building-highly-specialised-docker-images-example-for-net-b7bb177ab647
set -x #trace on
set -e #break on error

user_id=$1
hardening_platform=$2

echo "Using user ID: $user_id"
echo "Hardening for platform: $hardening_platform"

# Initial list of system directories
all_sysdirs="
  /bin
  /etc
  /lib
  /lib64
  /sbin
  /usr
"

# Filter out only existing directories
sysdirs=""
for dir in $all_sysdirs; do
  if [ -d "$dir" ]; then
    sysdirs="$sysdirs $dir"
  else
    echo "Directory $dir not found. Skipping."
  fi
done

# Fix shadow file for the user (remove ! which indicates locked account)
if [ -f /etc/shadow ]; then
  sed -i "s/${user_id}:!:/${user_id}:x:/" /etc/shadow 2>/dev/null || true
fi

# Remove unnecessary user accounts - keep only the specified user, root, and node
if [ -f /etc/group ]; then
  # Create a temporary file with only the users we want to keep
  grep -E "(^${user_id}:|^root:|^node:)" /etc/group > /tmp/group.new 2>/dev/null || true
  if [ -s /tmp/group.new ]; then
    mv /tmp/group.new /etc/group
  fi
fi

if [ -f /etc/passwd ]; then
  # Create a temporary file with only the users we want to keep
  grep -E "(^${user_id}:|^root:|^node:)" /etc/passwd > /tmp/passwd.new 2>/dev/null || true
  if [ -s /tmp/passwd.new ]; then
    mv /tmp/passwd.new /etc/passwd
  fi
fi

if [ -f /etc/shadow ]; then
  # Create a temporary file with only the users we want to keep
  grep -E "(^${user_id}:|^root:|^node:)" /etc/shadow > /tmp/shadow.new 2>/dev/null || true
  if [ -s /tmp/shadow.new ]; then
    mv /tmp/shadow.new /etc/shadow
  fi
fi

# Remove files generated by sed commands above (group-, passwd- and shadow-)
if [ -n "$sysdirs" ]; then
  find $sysdirs -xdev -type f -name "*-" -exec rm -f {} + 2>/dev/null || true
fi

# Ensure system dirs are owned by root and not writable by anybody else
if [ -n "$sysdirs" ]; then
  find $sysdirs -xdev -type d \
    -exec chown root:root {} \; \
    -exec chmod 0755 {} \; 2>/dev/null || true
fi

# Remove existing crontabs, if any
rm -fr /var/spool/cron 2>/dev/null || true

# Remove kernel tunables since we do not need them in containers
rm -fr /etc/sysctl* 2>/dev/null || true
rm -fr /etc/modprobe.d 2>/dev/null || true
rm -fr /etc/modules 2>/dev/null || true

# Remove fstab since we do not need them in containers
rm -f /etc/fstab 2>/dev/null || true

# Remove all but essential admin commands
if [ -d /usr/sbin ]; then
  find /usr/sbin ! -type d \
    -a ! -name nologin \
    -delete 2>/dev/null || true
fi

# Remove all but essential executable commands for Node.js with Chromium
case $hardening_platform in
  nodejs)
    if [ -d /usr/bin ]; then
      # Instead of removing everything, remove specific dangerous binaries
      # This is safer for images that use busybox or other multi-tool binaries
      dangerous_binaries="wget curl ftp telnet ssh scp rsync nc netcat nmap socat openssl gpg"
      
      for dangerous in $dangerous_binaries; do
        if [ -f "/usr/bin/$dangerous" ]; then
          rm -f "/usr/bin/$dangerous" 2>/dev/null || true
          echo "Removed dangerous binary: $dangerous"
        fi
      done
      
      # Remove any package managers we don't need (keep npm for Node.js)
      pkg_managers="apk apt apt-get yum dnf zypper pacman pip pip3"
      for pkg in $pkg_managers; do
        if [ -f "/usr/bin/$pkg" ]; then
          rm -f "/usr/bin/$pkg" 2>/dev/null || true
          echo "Removed package manager: $pkg"
        fi
      done
    fi
    ;;
  *)
    if [ -d /usr/bin ]; then
      # For other platforms, be even more conservative
      dangerous_binaries="wget curl ftp telnet ssh scp rsync nc netcat nmap socat"
      
      for dangerous in $dangerous_binaries; do
        if [ -f "/usr/bin/$dangerous" ]; then
          rm -f "/usr/bin/$dangerous" 2>/dev/null || true
          echo "Removed dangerous binary: $dangerous"
        fi
      done
    fi
    ;;
esac

# Remove broken symlinks (because we removed the targets above)
if [ -n "$sysdirs" ]; then
  find $sysdirs -xdev -type l -exec test ! -e {} \; -delete 2>/dev/null || true
fi

# Clean up temporary files
rm -rf /tmp/* 2>/dev/null || true
rm -rf /var/tmp/* 2>/dev/null || true

# Remove package manager caches and unnecessary files
rm -rf /var/cache/apk/* 2>/dev/null || true
rm -rf /root/.npm 2>/dev/null || true
rm -rf /home/*/.npm 2>/dev/null || true

# Remove documentation and man pages to reduce attack surface
rm -rf /usr/share/doc 2>/dev/null || true
rm -rf /usr/share/man 2>/dev/null || true
rm -rf /usr/share/info 2>/dev/null || true

echo "Hardening script completed successfully for user ID: $user_id" 