#!/bin/bash

# Quick script to add SSH key via DigitalOcean Console
# Copy and paste these commands into the droplet console

echo "=========================================="
echo "Add SSH Key to Droplet via Console"
echo "=========================================="
echo ""
echo "Copy and paste these commands into the DigitalOcean Console:"
echo ""
echo "---"
echo ""
echo "# Create .ssh directory"
echo "mkdir -p ~/.ssh"
echo "chmod 700 ~/.ssh"
echo ""
echo "# Add your public key"
echo "echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOeEi8btficCLzA+UZGTmUdYJe/IpH2LGGw/gzyaccm/ progrc-droplet-access' >> ~/.ssh/authorized_keys"
echo ""
echo "# Set correct permissions"
echo "chmod 600 ~/.ssh/authorized_keys"
echo "chown root:root ~/.ssh/authorized_keys"
echo ""
echo "# Verify"
echo "cat ~/.ssh/authorized_keys"
echo ""
echo "---"
echo ""
echo "Steps:"
echo "1. Go to: https://cloud.digitalocean.com/droplets"
echo "2. Click droplet → Access → Launch Droplet Console"
echo "3. Paste the commands above"
echo "4. Test SSH from your local machine"
echo ""
