import { MigrationInterface, QueryRunner } from "typeorm";

export class AddNewSSPTemplateSections1737465698107 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            INSERT INTO public.templates_section
(template_id, title, "level", section_id, outline_search_key, html_content, description, s3_path, metadata, created_at, is_active)
VALUES(4, 'ProGRC Initial Assessment & Plan Report', NULL, '422d352c-27f4-4bcc-a79c-e214d0accb13', NULL, '<p>{progrc_logo}</p>
<h1>ProGRC Initial Assessment &amp; Plan Report</h1>
<p>This report provides a summary review of the system’s level of readiness to complete the FedRAMP® System Security Plan (SSP): Appendix A. It is an interim report that we will use to gather data, identify gaps, and prepare to implement controls for the full assessment. </p>
<p><strong>for</strong>  </p>
<p>{org_logo} </p>
<p><strong>Organization:</strong> {org_name}</p>
<p><strong>System:</strong> {app_name}</p>
<p><strong>Prepared By:</strong> {org_name}</p>
<p><strong>Report Version:</strong> {assessment_version}</p>
<p><strong>Prepared on:</strong> {assessment_updated_date}</p>
<p><strong>ProGRC CSM:</strong> {org_designated_csm}</p>', NULL, NULL, '{"isLLMParsing": false}'::json, now(), true),
        (4, 'Executive Summary', NULL, 'fdafe850-400b-43f1-a48a-be6f579c2b61', NULL, '<h1>Executive Summary</h1>
<h2>{app_name}</h2>
<p><strong>Description:</strong> {app_description}</p>
<p><strong>Compliance Standard:</strong> {standard_name}</p>
<p><strong>Controls:</strong> {total_controls_in_standard} </p>
<p><strong>Implemented:</strong> {total_implemented_controls}</p>
<p><strong>Partially Implemented:</strong> {total_partially_implemented_controls}</p>
<p><strong>Not Implemented:</strong> {total_not_implemented_controls} </p>
<p><strong>Excepted Controls:</strong> {total_excepted_controls}</p>', NULL, NULL, '{"isLLMParsing": false}'::json, now(), true),
        (4, 'Report', NULL, 'c7b0881c-8187-40f1-8801-66f273d84332', NULL, '<h1>Documented and Assessed Control</h1>
<h2>{control_family_name}</h2>
<h3>{control_id} {control_name}</h3>
<h4>{control_id} Control Discussion</h4>
<p>{control_text}</p>
<h4>{control_id} Control Requirement(s)</h4>
<p>{control_discussion}</p>
<h4>{control_id} Additional Control Requirement(s)</h4>
<p>{control_additional_params}</p>
<h4>{control_id} Control Assessment Results</h4>
<p><strong>Responsible Role:</strong>  {app_admin}</p>
<p><strong>Responsibility:</strong>  {responsibility}</p>
<p><strong>Implementation Status:</strong>  {implementation_status}</p>
<p><strong>Implementation Description:</strong> {implementation_explanation}</p>
<p><strong>Exceptions:</strong> {control_exception} </p>
<p><strong>Artifacts:</strong> These are files that were uploaded by the user to explain the implementation of the control. Detailed references for these sources are available by request or through the ProGRC application. 
{list_of_referenced_sources}</p>
<p><strong>Evidence:</strong> These evidences were uploaded by the user to explain their implementation of the control.
{list_of_evidences}</p>
<h4>{control_id} Remediation Plan</h4>
<p>The following is a list of recommendations generated by the ProGRC application and whether the user has accepted each recommendation. 
{recommendation_plan_table}</p>', NULL, NULL, '{"isLLMParsing": false}'::json, now(), true);
        ;
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DELETE FROM public.templates_section WHERE template_id = 4;`);
    }

}
