import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateTemplateFormattingForReportSection1738304934152 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            UPDATE public.templates_section set html_content = '<h1>Documented and Assessed Control</h1>
<h2>{control_family_name}</h2>
<h3>{control_id} {control_name}</h3>
<h4>{control_id} Control Discussion</h4>
<div>{control_text}</div>
<h4>{control_id} Control Requirement(s)</h4>
<div>{control_discussion}</div>
<h4>{control_id} Additional Control Requirement(s)</h4>
<div>{control_additional_params}</div>
<h4>{control_id} Control Assessment Results</h4>
<p><strong>Responsible Role:</strong>  {app_admin}</p>
<p><strong>Responsibility:</strong>  {responsibility}</p>
<p><strong>Implementation Status:</strong>  {implementation_status}</p>
<p><strong>Implementation Description:</strong></p>
<div>{implementation_explanation}</div>
<p><strong>Exceptions:</strong> {control_exception} </p>
<p><strong>Artifacts:</strong> These are files that were uploaded by the user to explain the implementation of the control. Detailed references for these sources are available by request or throug the Kovr.ai application. 
{list_of_referenced_sources}</p>
<p><strong>Evidences:</strong> These evidences were uploaded by the user to explain their implementation of the control.
{list_of_evidences}</p>
<h4>{control_id} Remediation Plan</h4>
<div>The following is a list of recommendations generated by the Kovr. ai application and whether the user has accepted each recommendation. </div>
<div>{recommendation_plan_table}</div>' where template_id = 4 and section_id = 'c7b0881c-8187-40f1-8801-66f273d84332';
        ;
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            UPDATE public.templates_section set html_content = '<h1>Documented and Assessed Control</h1>
<h2>{control_family_name}</h2>
<h3>{control_id} {control_name}</h3>
<h4>{control_id} Control Discussion</h4>
<p>{control_text}</p>
<h4>{control_id} Control Requirement(s)</h4>
<p>{control_discussion}</p>
<h4>{control_id} Additional Control Requirement(s)</h4>
<p>{control_additional_params}</p>
<h4>{control_id} Control Assessment Results</h4>
<p><strong>Responsible Role:</strong>  {app_admin}</p>
<p><strong>Responsibility:</strong>  {responsibility}</p>
<p><strong>Implementation Status:</strong>  {implementation_status}</p>
<p><strong>Implementation Description:</strong><p>
<p>{implementation_explanation}</p>
<p><strong>Exceptions:</strong> {control_exception} </p>
<p><strong>Artifacts:</strong> These are files that were uploaded by the user to explain the implementation of the control. Detailed references for these sources are available by request or throug the Kovr.ai application. 
{list_of_referenced_sources}</p>
<p><strong>Evidences:</strong> These evidences were uploaded by the user to explain their implementation of the control.
{list_of_evidences}</p>
<h4>{control_id} Remediation Plan</h4>
<p>The following is a list of recommendations generated by the Kovr. ai application and whether the user has accepted each recommendation. 
{recommendation_plan_table}</p>' where template_id = 4 and section_id = 'c7b0881c-8187-40f1-8801-66f273d84332';
        ;
        `);
    }

}
